// ISO 3166-1 alpha-2 country codes with names (sorted alphabetically)
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (DRC)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "North Korea" },
  { code: "KR", name: "South Korea" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macau" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "VI", name: "Virgin Islands (U.S.)" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];


// Subdivisions (states/provinces) keyed by country code.
// Only countries with commonly-used subdivisions are included.
export const SUBDIVISIONS: Record<string, { code: string; name: string }[]> = {
  US: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "DC", name: "District of Columbia" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
  ],

  CA: [
    { code: "AB", name: "Alberta" },
    { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" },
    { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" },
    { code: "NS", name: "Nova Scotia" },
    { code: "NT", name: "Northwest Territories" },
    { code: "NU", name: "Nunavut" },
    { code: "ON", name: "Ontario" },
    { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" },
    { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],

  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA", name: "Western Australia" },
  ],

  IN: [
    { code: "AN", name: "Andaman and Nicobar Islands" },
    { code: "AP", name: "Andhra Pradesh" },
    { code: "AR", name: "Arunachal Pradesh" },
    { code: "AS", name: "Assam" },
    { code: "BR", name: "Bihar" },
    { code: "CH", name: "Chandigarh" },
    { code: "CT", name: "Chhattisgarh" },
    { code: "DL", name: "Delhi" },
    { code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" },
    { code: "HR", name: "Haryana" },
    { code: "HP", name: "Himachal Pradesh" },
    { code: "JK", name: "Jammu and Kashmir" },
    { code: "JH", name: "Jharkhand" },
    { code: "KA", name: "Karnataka" },
    { code: "KL", name: "Kerala" },
    { code: "MP", name: "Madhya Pradesh" },
    { code: "MH", name: "Maharashtra" },
    { code: "MN", name: "Manipur" },
    { code: "ML", name: "Meghalaya" },
    { code: "MZ", name: "Mizoram" },
    { code: "NL", name: "Nagaland" },
    { code: "OR", name: "Odisha" },
    { code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" },
    { code: "SK", name: "Sikkim" },
    { code: "TN", name: "Tamil Nadu" },
    { code: "TG", name: "Telangana" },
    { code: "TR", name: "Tripura" },
    { code: "UP", name: "Uttar Pradesh" },
    { code: "UT", name: "Uttarakhand" },
    { code: "WB", name: "West Bengal" },
  ],

  BR: [
    { code: "AC", name: "Acre" },
    { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" },
    { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" },
    { code: "CE", name: "Ceará" },
    { code: "DF", name: "Distrito Federal" },
    { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" },
    { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" },
    { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" },
    { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" },
    { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" },
    { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" },
    { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" },
    { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" },
    { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" },
    { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],

  MX: [
    { code: "AGU", name: "Aguascalientes" },
    { code: "BCN", name: "Baja California" },
    { code: "BCS", name: "Baja California Sur" },
    { code: "CAM", name: "Campeche" },
    { code: "CHP", name: "Chiapas" },
    { code: "CHH", name: "Chihuahua" },
    { code: "CMX", name: "Ciudad de México" },
    { code: "COA", name: "Coahuila" },
    { code: "COL", name: "Colima" },
    { code: "DUR", name: "Durango" },
    { code: "GUA", name: "Guanajuato" },
    { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" },
    { code: "JAL", name: "Jalisco" },
    { code: "MEX", name: "México" },
    { code: "MIC", name: "Michoacán" },
    { code: "MOR", name: "Morelos" },
    { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" },
    { code: "OAX", name: "Oaxaca" },
    { code: "PUE", name: "Puebla" },
    { code: "QUE", name: "Querétaro" },
    { code: "ROO", name: "Quintana Roo" },
    { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" },
    { code: "SON", name: "Sonora" },
    { code: "TAB", name: "Tabasco" },
    { code: "TAM", name: "Tamaulipas" },
    { code: "TLA", name: "Tlaxcala" },
    { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" },
    { code: "ZAC", name: "Zacatecas" },
  ],
  DE: [
    { code: "BW", name: "Baden-Württemberg" },
    { code: "BY", name: "Bavaria" },
    { code: "BE", name: "Berlin" },
    { code: "BB", name: "Brandenburg" },
    { code: "HB", name: "Bremen" },
    { code: "HH", name: "Hamburg" },
    { code: "HE", name: "Hesse" },
    { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Lower Saxony" },
    { code: "NW", name: "North Rhine-Westphalia" },
    { code: "RP", name: "Rhineland-Palatinate" },
    { code: "SL", name: "Saarland" },
    { code: "SN", name: "Saxony" },
    { code: "ST", name: "Saxony-Anhalt" },
    { code: "SH", name: "Schleswig-Holstein" },
    { code: "TH", name: "Thuringia" },
  ],
  GB: [
    { code: "ENG", name: "England" },
    { code: "NIR", name: "Northern Ireland" },
    { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" },
  ],
  JP: [
    { code: "01", name: "Hokkaido" },
    { code: "02", name: "Aomori" },
    { code: "03", name: "Iwate" },
    { code: "04", name: "Miyagi" },
    { code: "05", name: "Akita" },
    { code: "06", name: "Yamagata" },
    { code: "07", name: "Fukushima" },
    { code: "08", name: "Ibaraki" },
    { code: "09", name: "Tochigi" },
    { code: "10", name: "Gunma" },
    { code: "11", name: "Saitama" },
    { code: "12", name: "Chiba" },
    { code: "13", name: "Tokyo" },
    { code: "14", name: "Kanagawa" },
    { code: "15", name: "Niigata" },
    { code: "16", name: "Toyama" },
    { code: "17", name: "Ishikawa" },
    { code: "18", name: "Fukui" },
    { code: "19", name: "Yamanashi" },
    { code: "20", name: "Nagano" },
    { code: "21", name: "Gifu" },
    { code: "22", name: "Shizuoka" },
    { code: "23", name: "Aichi" },
    { code: "24", name: "Mie" },
    { code: "25", name: "Shiga" },
    { code: "26", name: "Kyoto" },
    { code: "27", name: "Osaka" },
    { code: "28", name: "Hyogo" },
    { code: "29", name: "Nara" },
    { code: "30", name: "Wakayama" },
    { code: "31", name: "Tottori" },
    { code: "32", name: "Shimane" },
    { code: "33", name: "Okayama" },
    { code: "34", name: "Hiroshima" },
    { code: "35", name: "Yamaguchi" },
    { code: "36", name: "Tokushima" },
    { code: "37", name: "Kagawa" },
    { code: "38", name: "Ehime" },
    { code: "39", name: "Kochi" },
    { code: "40", name: "Fukuoka" },
    { code: "41", name: "Saga" },
    { code: "42", name: "Nagasaki" },
    { code: "43", name: "Kumamoto" },
    { code: "44", name: "Oita" },
    { code: "45", name: "Miyazaki" },
    { code: "46", name: "Kagoshima" },
    { code: "47", name: "Okinawa" },
  ],
  CN: [
    { code: "AH", name: "Anhui" },
    { code: "BJ", name: "Beijing" },
    { code: "CQ", name: "Chongqing" },
    { code: "FJ", name: "Fujian" },
    { code: "GS", name: "Gansu" },
    { code: "GD", name: "Guangdong" },
    { code: "GX", name: "Guangxi" },
    { code: "GZ", name: "Guizhou" },
    { code: "HI", name: "Hainan" },
    { code: "HE", name: "Hebei" },
    { code: "HL", name: "Heilongjiang" },
    { code: "HA", name: "Henan" },
    { code: "HB", name: "Hubei" },
    { code: "HN", name: "Hunan" },
    { code: "JS", name: "Jiangsu" },
    { code: "JX", name: "Jiangxi" },
    { code: "JL", name: "Jilin" },
    { code: "LN", name: "Liaoning" },
    { code: "NM", name: "Inner Mongolia" },
    { code: "NX", name: "Ningxia" },
    { code: "QH", name: "Qinghai" },
    { code: "SN", name: "Shaanxi" },
    { code: "SD", name: "Shandong" },
    { code: "SH", name: "Shanghai" },
    { code: "SX", name: "Shanxi" },
    { code: "SC", name: "Sichuan" },
    { code: "TJ", name: "Tianjin" },
    { code: "XZ", name: "Tibet" },
    { code: "XJ", name: "Xinjiang" },
    { code: "YN", name: "Yunnan" },
    { code: "ZJ", name: "Zhejiang" },
  ],
  IT: [
    { code: "AG", name: "Agrigento" },
    { code: "BO", name: "Bologna" },
    { code: "FI", name: "Florence" },
    { code: "GE", name: "Genoa" },
    { code: "MI", name: "Milan" },
    { code: "NA", name: "Naples" },
    { code: "PA", name: "Palermo" },
    { code: "RM", name: "Rome" },
    { code: "TO", name: "Turin" },
    { code: "VE", name: "Venice" },
  ],
  ES: [
    { code: "AN", name: "Andalusia" },
    { code: "AR", name: "Aragon" },
    { code: "AS", name: "Asturias" },
    { code: "IB", name: "Balearic Islands" },
    { code: "PV", name: "Basque Country" },
    { code: "CN", name: "Canary Islands" },
    { code: "CB", name: "Cantabria" },
    { code: "CL", name: "Castile and León" },
    { code: "CM", name: "Castilla-La Mancha" },
    { code: "CT", name: "Catalonia" },
    { code: "EX", name: "Extremadura" },
    { code: "GA", name: "Galicia" },
    { code: "RI", name: "La Rioja" },
    { code: "MD", name: "Madrid" },
    { code: "MC", name: "Murcia" },
    { code: "NC", name: "Navarre" },
    { code: "VC", name: "Valencia" },
  ],
  FR: [
    { code: "ARA", name: "Auvergne-Rhône-Alpes" },
    { code: "BFC", name: "Bourgogne-Franche-Comté" },
    { code: "BRE", name: "Brittany" },
    { code: "CVL", name: "Centre-Val de Loire" },
    { code: "COR", name: "Corsica" },
    { code: "GES", name: "Grand Est" },
    { code: "HDF", name: "Hauts-de-France" },
    { code: "IDF", name: "Île-de-France" },
    { code: "NOR", name: "Normandy" },
    { code: "NAQ", name: "Nouvelle-Aquitaine" },
    { code: "OCC", name: "Occitanie" },
    { code: "PDL", name: "Pays de la Loire" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  ],
  NG: [
    { code: "AB", name: "Abia" },
    { code: "AD", name: "Adamawa" },
    { code: "AK", name: "Akwa Ibom" },
    { code: "AN", name: "Anambra" },
    { code: "BA", name: "Bauchi" },
    { code: "BY", name: "Bayelsa" },
    { code: "BE", name: "Benue" },
    { code: "BO", name: "Borno" },
    { code: "CR", name: "Cross River" },
    { code: "DE", name: "Delta" },
    { code: "EB", name: "Ebonyi" },
    { code: "ED", name: "Edo" },
    { code: "EK", name: "Ekiti" },
    { code: "EN", name: "Enugu" },
    { code: "FC", name: "FCT Abuja" },
    { code: "GO", name: "Gombe" },
    { code: "IM", name: "Imo" },
    { code: "JI", name: "Jigawa" },
    { code: "KD", name: "Kaduna" },
    { code: "KN", name: "Kano" },
    { code: "KT", name: "Katsina" },
    { code: "KE", name: "Kebbi" },
    { code: "KO", name: "Kogi" },
    { code: "KW", name: "Kwara" },
    { code: "LA", name: "Lagos" },
    { code: "NA", name: "Nasarawa" },
    { code: "NI", name: "Niger" },
    { code: "OG", name: "Ogun" },
    { code: "ON", name: "Ondo" },
    { code: "OS", name: "Osun" },
    { code: "OY", name: "Oyo" },
    { code: "PL", name: "Plateau" },
    { code: "RI", name: "Rivers" },
    { code: "SO", name: "Sokoto" },
    { code: "TA", name: "Taraba" },
    { code: "YO", name: "Yobe" },
    { code: "ZA", name: "Zamfara" },
  ],
  EG: [
    { code: "ALX", name: "Alexandria" },
    { code: "ASN", name: "Aswan" },
    { code: "AST", name: "Asyut" },
    { code: "BH", name: "Beheira" },
    { code: "CAI", name: "Cairo" },
    { code: "DK", name: "Dakahlia" },
    { code: "DT", name: "Damietta" },
    { code: "FYM", name: "Faiyum" },
    { code: "GH", name: "Gharbia" },
    { code: "GZ", name: "Giza" },
    { code: "IS", name: "Ismailia" },
    { code: "KFS", name: "Kafr el-Sheikh" },
    { code: "LX", name: "Luxor" },
    { code: "MN", name: "Minya" },
    { code: "MNF", name: "Monufia" },
    { code: "PTS", name: "Port Said" },
    { code: "KB", name: "Qalyubia" },
    { code: "KN", name: "Qena" },
    { code: "SHR", name: "Sharqia" },
    { code: "SHG", name: "Sohag" },
    { code: "SUZ", name: "Suez" },
  ],
  SA: [
    { code: "01", name: "Riyadh" },
    { code: "02", name: "Makkah" },
    { code: "03", name: "Madinah" },
    { code: "04", name: "Eastern Province" },
    { code: "05", name: "Qassim" },
    { code: "06", name: "Ha'il" },
    { code: "07", name: "Tabuk" },
    { code: "08", name: "Northern Borders" },
    { code: "09", name: "Jazan" },
    { code: "10", name: "Najran" },
    { code: "11", name: "Al Bahah" },
    { code: "12", name: "Al Jawf" },
    { code: "14", name: "Asir" },
  ],
  AE: [
    { code: "AZ", name: "Abu Dhabi" },
    { code: "AJ", name: "Ajman" },
    { code: "DU", name: "Dubai" },
    { code: "FU", name: "Fujairah" },
    { code: "RK", name: "Ras Al Khaimah" },
    { code: "SH", name: "Sharjah" },
    { code: "UQ", name: "Umm Al Quwain" },
  ],
  ZA: [
    { code: "EC", name: "Eastern Cape" },
    { code: "FS", name: "Free State" },
    { code: "GP", name: "Gauteng" },
    { code: "KZN", name: "KwaZulu-Natal" },
    { code: "LP", name: "Limpopo" },
    { code: "MP", name: "Mpumalanga" },
    { code: "NC", name: "Northern Cape" },
    { code: "NW", name: "North West" },
    { code: "WC", name: "Western Cape" },
  ],
  PK: [
    { code: "BA", name: "Balochistan" },
    { code: "IS", name: "Islamabad" },
    { code: "KP", name: "Khyber Pakhtunkhwa" },
    { code: "PB", name: "Punjab" },
    { code: "SD", name: "Sindh" },
  ],
  PH: [
    { code: "NCR", name: "Metro Manila" },
    { code: "CAR", name: "Cordillera" },
    { code: "01", name: "Ilocos" },
    { code: "02", name: "Cagayan Valley" },
    { code: "03", name: "Central Luzon" },
    { code: "4A", name: "CALABARZON" },
    { code: "05", name: "Bicol" },
    { code: "06", name: "Western Visayas" },
    { code: "07", name: "Central Visayas" },
    { code: "08", name: "Eastern Visayas" },
    { code: "09", name: "Zamboanga Peninsula" },
    { code: "10", name: "Northern Mindanao" },
    { code: "11", name: "Davao" },
    { code: "12", name: "SOCCSKSARGEN" },
    { code: "13", name: "Caraga" },
    { code: "BARMM", name: "Bangsamoro" },
  ],
};

// Helper to get subdivision label based on country
export function getSubdivisionLabel(countryCode: string): string {
  switch (countryCode) {
    case "US": return "State";
    case "CA": return "Province";
    case "AU": return "State/Territory";
    case "GB": return "Country";
    case "JP": return "Prefecture";
    case "CN": return "Province";
    case "DE": return "State";
    case "BR": return "State";
    case "IN": return "State";
    case "MX": return "State";
    case "IT": return "Province";
    case "ES": return "Community";
    case "FR": return "Region";
    case "NG": return "State";
    case "EG": return "Governorate";
    case "SA": return "Region";
    case "AE": return "Emirate";
    case "ZA": return "Province";
    case "PK": return "Province";
    case "PH": return "Region";
    default: return "State / Province";
  }
}
