
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  reviewDepth: 'reviewDepth',
  defaultLanguage: 'defaultLanguage',
  autoReview: 'autoReview',
  includeSecurityChecks: 'includeSecurityChecks',
  includePerfSuggestions: 'includePerfSuggestions',
  preferredModel: 'preferredModel',
  banned: 'banned',
  bannedReason: 'bannedReason',
  desktopNotifications: 'desktopNotifications',
  emailNotifications: 'emailNotifications',
  notificationSoundEnabled: 'notificationSoundEnabled',
  notifyReviewApproved: 'notifyReviewApproved',
  notifyReviewAssigned: 'notifyReviewAssigned',
  notifyReviewChangesRequested: 'notifyReviewChangesRequested',
  notifyReviewCompleted: 'notifyReviewCompleted',
  notifyReviewFailed: 'notifyReviewFailed',
  notifyScheduledScanCompleted: 'notifyScheduledScanCompleted',
  notifyTeamInvites: 'notifyTeamInvites',
  notifyTeamMemberAdded: 'notifyTeamMemberAdded',
  planId: 'planId',
  planExpiresAt: 'planExpiresAt',
  planStartedAt: 'planStartedAt',
  billingCycle: 'billingCycle',
  pendingPlanId: 'pendingPlanId',
  pendingBillingCycle: 'pendingBillingCycle',
  accountCredit: 'accountCredit',
  overrideReposLimit: 'overrideReposLimit',
  overrideReviewsLimit: 'overrideReviewsLimit',
  overrideSeatsLimit: 'overrideSeatsLimit'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RepositoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  teamId: 'teamId',
  githubId: 'githubId',
  name: 'name',
  fullName: 'fullName',
  private: 'private',
  htmlUrl: 'htmlUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  userId: 'userId',
  prNumber: 'prNumber',
  prTitle: 'prTitle',
  prUrl: 'prUrl',
  status: 'status',
  summary: 'summary',
  riskScore: 'riskScore',
  comments: 'comments',
  qualityMetrics: 'qualityMetrics',
  error: 'error',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  parentReviewId: 'parentReviewId',
  resolvedComments: 'resolvedComments'
};

exports.Prisma.ReviewFeedbackScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  userId: 'userId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt'
};

exports.Prisma.SecurityIssueScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  severity: 'severity',
  type: 'type',
  cveId: 'cveId',
  cweId: 'cweId',
  packageName: 'packageName',
  packageVersion: 'packageVersion',
  title: 'title',
  description: 'description',
  remediation: 'remediation',
  affectedLines: 'affectedLines',
  falsePositive: 'falsePositive',
  resolved: 'resolved',
  resolvedAt: 'resolvedAt',
  resolvedBy: 'resolvedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewThreadScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  file: 'file',
  line: 'line',
  resolved: 'resolved',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewThreadCommentScalarFieldEnum = {
  id: 'id',
  threadId: 'threadId',
  userId: 'userId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewThreadCommentReactionScalarFieldEnum = {
  id: 'id',
  commentId: 'commentId',
  userId: 'userId',
  emoji: 'emoji',
  createdAt: 'createdAt'
};

exports.Prisma.ReviewApprovalScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  userId: 'userId',
  state: 'state',
  body: 'body',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewAssignmentScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  assigneeId: 'assigneeId',
  assignedBy: 'assignedBy',
  dueDate: 'dueDate',
  priority: 'priority',
  status: 'status',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.TeamActionScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  actionType: 'actionType',
  status: 'status',
  requestedBy: 'requestedBy',
  targetUserId: 'targetUserId',
  targetRepoId: 'targetRepoId',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resolvedAt: 'resolvedAt',
  resolvedBy: 'resolvedBy'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  link: 'link',
  read: 'read',
  createdAt: 'createdAt'
};

exports.Prisma.WebhookConfigScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  enabled: 'enabled',
  githubWebhookId: 'githubWebhookId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  scoreThreshold: 'scoreThreshold'
};

exports.Prisma.ScheduledScanConfigScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  enabled: 'enabled',
  cadence: 'cadence',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduledScanRunScalarFieldEnum = {
  id: 'id',
  configId: 'configId',
  triggeredAt: 'triggeredAt',
  completedAt: 'completedAt',
  status: 'status',
  reviewsQueued: 'reviewsQueued',
  summary: 'summary'
};

exports.Prisma.GitHubCommentScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  githubReviewId: 'githubReviewId',
  prNumber: 'prNumber',
  repositoryId: 'repositoryId',
  commitSha: 'commitSha',
  findingCount: 'findingCount',
  createdAt: 'createdAt'
};

exports.Prisma.GitHubStatusCheckScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  commitSha: 'commitSha',
  state: 'state',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BranchProtectionRecommendationScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  rule: 'rule',
  rationale: 'rationale',
  priority: 'priority',
  dismissed: 'dismissed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DiagramScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  type: 'type',
  status: 'status',
  definition: 'definition',
  nodes: 'nodes',
  edges: 'edges',
  error: 'error',
  generatedAt: 'generatedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  pattern: 'pattern',
  severity: 'severity',
  repositoryId: 'repositoryId',
  teamId: 'teamId',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.SystemSettingsScalarFieldEnum = {
  id: 'id',
  maintenanceMode: 'maintenanceMode',
  updatedAt: 'updatedAt',
  auditLogRetentionDays: 'auditLogRetentionDays',
  reviewRetentionDays: 'reviewRetentionDays',
  sessionRetentionDays: 'sessionRetentionDays',
  bannerColor: 'bannerColor',
  bannerEnabled: 'bannerEnabled',
  bannerLink: 'bannerLink',
  bannerLinkText: 'bannerLinkText',
  bannerText: 'bannerText'
};

exports.Prisma.SupportMessageScalarFieldEnum = {
  id: 'id',
  email: 'email',
  message: 'message',
  status: 'status',
  createdAt: 'createdAt',
  name: 'name',
  subject: 'subject',
  type: 'type',
  userId: 'userId'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  actorId: 'actorId',
  action: 'action',
  resource: 'resource',
  resourceId: 'resourceId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  country: 'country',
  city: 'city',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.SsoProviderScalarFieldEnum = {
  id: 'id',
  issuer: 'issuer',
  domain: 'domain',
  oidcConfig: 'oidcConfig',
  samlConfig: 'samlConfig',
  userId: 'userId',
  providerId: 'providerId',
  organizationId: 'organizationId',
  name: 'name',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomRoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  canViewReviews: 'canViewReviews',
  canTriggerReviews: 'canTriggerReviews',
  canManageRepositories: 'canManageRepositories',
  canManageTeams: 'canManageTeams',
  canViewAnalytics: 'canViewAnalytics',
  canManageUsers: 'canManageUsers',
  canAccessAdmin: 'canAccessAdmin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserCustomRoleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  roleId: 'roleId',
  assignedAt: 'assignedAt'
};

exports.Prisma.DiscountScalarFieldEnum = {
  id: 'id',
  code: 'code',
  description: 'description',
  type: 'type',
  value: 'value',
  planId: 'planId',
  maxUses: 'maxUses',
  usedCount: 'usedCount',
  active: 'active',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPriceOverrideScalarFieldEnum = {
  id: 'id',
  email: 'email',
  planId: 'planId',
  overrideMonthlyPrice: 'overrideMonthlyPrice',
  overrideYearlyPrice: 'overrideYearlyPrice',
  reason: 'reason',
  active: 'active',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PartnerDomainScalarFieldEnum = {
  id: 'id',
  domain: 'domain',
  companyName: 'companyName',
  planId: 'planId',
  overrideMonthlyPrice: 'overrideMonthlyPrice',
  overrideYearlyPrice: 'overrideYearlyPrice',
  note: 'note',
  active: 'active',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PricingPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tagline: 'tagline',
  monthlyPrice: 'monthlyPrice',
  visible: 'visible',
  highlight: 'highlight',
  features: 'features',
  reposLimit: 'reposLimit',
  reviewsLimit: 'reviewsLimit',
  seatsLimit: 'seatsLimit',
  privateRepos: 'privateRepos',
  sortOrder: 'sortOrder',
  accentColor: 'accentColor',
  cta: 'cta',
  badge: 'badge',
  updatedAt: 'updatedAt'
};

exports.Prisma.CapabilityScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  description: 'description',
  kind: 'kind',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlanCapabilityScalarFieldEnum = {
  planId: 'planId',
  capabilityId: 'capabilityId',
  enabled: 'enabled'
};

exports.Prisma.PricingSettingsScalarFieldEnum = {
  id: 'id',
  pricingEnabled: 'pricingEnabled',
  annualDiscount: 'annualDiscount',
  trialDays: 'trialDays',
  trialPlan: 'trialPlan',
  gracePeriodDays: 'gracePeriodDays',
  refundEnabled: 'refundEnabled',
  refundWindowDays: 'refundWindowDays',
  taxEnabled: 'taxEnabled',
  taxRate: 'taxRate',
  promoCodesAtCheckout: 'promoCodesAtCheckout',
  freeSignupEnabled: 'freeSignupEnabled',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  status: 'status',
  planId: 'planId',
  billingCycle: 'billingCycle',
  description: 'description',
  fawaterakInvoiceId: 'fawaterakInvoiceId',
  fawaterakInvoiceKey: 'fawaterakInvoiceKey',
  paymentMethodUsed: 'paymentMethodUsed',
  referenceNumber: 'referenceNumber',
  successToken: 'successToken',
  currency: 'currency',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  idempotencyKey: 'idempotencyKey',
  version: 'version'
};

exports.Prisma.PaymentEventScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  eventType: 'eventType',
  source: 'source',
  metadata: 'metadata',
  rawPayload: 'rawPayload',
  createdAt: 'createdAt'
};

exports.Prisma.WebhookDedupScalarFieldEnum = {
  id: 'id',
  gatewayEventId: 'gatewayEventId',
  eventType: 'eventType',
  receivedAt: 'receivedAt'
};

exports.Prisma.UserDiscountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  discountId: 'discountId',
  appliedAt: 'appliedAt'
};

exports.Prisma.BillingInfoScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  state: 'state',
  zip: 'zip',
  country: 'country',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentMethodScalarFieldEnum = {
  id: 'id',
  billingInfoId: 'billingInfoId',
  cardBrand: 'cardBrand',
  lastFour: 'lastFour',
  expiryMonth: 'expiryMonth',
  expiryYear: 'expiryYear',
  isDefault: 'isDefault',
  fingerprint: 'fingerprint',
  fawaterakToken: 'fawaterakToken',
  customerUniqueId: 'customerUniqueId',
  cardTokenUniqueId: 'cardTokenUniqueId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LegalPageScalarFieldEnum = {
  slug: 'slug',
  title: 'title',
  content: 'content',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  category: 'category',
  resolved: 'resolved',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  subject: 'subject',
  body: 'body',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.UserRole = exports.$Enums.UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

exports.ReviewStatus = exports.$Enums.ReviewStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.SecuritySeverity = exports.$Enums.SecuritySeverity = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFO: 'INFO'
};

exports.SecurityIssueType = exports.$Enums.SecurityIssueType = {
  VULNERABILITY: 'VULNERABILITY',
  SECRET_EXPOSURE: 'SECRET_EXPOSURE',
  OWASP_TOP_10: 'OWASP_TOP_10',
  CODE_QUALITY: 'CODE_QUALITY',
  CWE: 'CWE'
};

exports.ReviewApprovalState = exports.$Enums.ReviewApprovalState = {
  APPROVED: 'APPROVED',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
  COMMENTED: 'COMMENTED'
};

exports.AssignmentPriority = exports.$Enums.AssignmentPriority = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

exports.AssignmentStatus = exports.$Enums.AssignmentStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

exports.TeamRole = exports.$Enums.TeamRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
};

exports.ActionType = exports.$Enums.ActionType = {
  INVITE_MEMBER: 'INVITE_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  UPDATE_ROLE: 'UPDATE_ROLE',
  SHARE_REPOSITORY: 'SHARE_REPOSITORY',
  UNSHARE_REPOSITORY: 'UNSHARE_REPOSITORY',
  DELETE_TEAM: 'DELETE_TEAM',
  REVIEW_PR: 'REVIEW_PR',
  APPROVE_DISCUSSION: 'APPROVE_DISCUSSION'
};

exports.ActionStatus = exports.$Enums.ActionStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  TEAM_INVITE: 'TEAM_INVITE',
  TEAM_MEMBER_ADDED: 'TEAM_MEMBER_ADDED',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',
  REVIEW_FAILED: 'REVIEW_FAILED',
  SCHEDULED_SCAN_COMPLETED: 'SCHEDULED_SCAN_COMPLETED',
  REVIEW_ASSIGNED: 'REVIEW_ASSIGNED',
  REVIEW_APPROVED: 'REVIEW_APPROVED',
  REVIEW_CHANGES_REQUESTED: 'REVIEW_CHANGES_REQUESTED'
};

exports.ScanCadence = exports.$Enums.ScanCadence = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY'
};

exports.ScanRunStatus = exports.$Enums.ScanRunStatus = {
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.GitHubCheckState = exports.$Enums.GitHubCheckState = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  ERROR: 'ERROR'
};

exports.RecommendationPriority = exports.$Enums.RecommendationPriority = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

exports.DiagramType = exports.$Enums.DiagramType = {
  ERD: 'ERD'
};

exports.DiagramStatus = exports.$Enums.DiagramStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.RuleSeverity = exports.$Enums.RuleSeverity = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

exports.DiscountType = exports.$Enums.DiscountType = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  PAID: 'PAID',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PROCESSING: 'PROCESSING',
  AUTHORIZED: 'AUTHORIZED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
  INITIATED: 'INITIATED'
};

exports.PaymentEventType = exports.$Enums.PaymentEventType = {
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_AUTHORIZED: 'PAYMENT_AUTHORIZED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_SUCCEEDED: 'REFUND_SUCCEEDED',
  REFUND_FAILED: 'REFUND_FAILED',
  DISPUTE_OPENED: 'DISPUTE_OPENED',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  CREDIT_APPLIED: 'CREDIT_APPLIED'
};

exports.MessageCategory = exports.$Enums.MessageCategory = {
  CONTACT: 'CONTACT',
  FEEDBACK: 'FEEDBACK',
  REVIEW_FEEDBACK: 'REVIEW_FEEDBACK',
  MAINTENANCE_FEEDBACK: 'MAINTENANCE_FEEDBACK'
};

exports.EmailTemplateCategory = exports.$Enums.EmailTemplateCategory = {
  ONBOARDING: 'ONBOARDING',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  FEATURE: 'FEATURE',
  NEWSLETTER: 'NEWSLETTER',
  TRANSACTIONAL: 'TRANSACTIONAL',
  GENERAL: 'GENERAL'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Repository: 'Repository',
  Review: 'Review',
  ReviewFeedback: 'ReviewFeedback',
  SecurityIssue: 'SecurityIssue',
  ReviewThread: 'ReviewThread',
  ReviewThreadComment: 'ReviewThreadComment',
  ReviewThreadCommentReaction: 'ReviewThreadCommentReaction',
  ReviewApproval: 'ReviewApproval',
  ReviewAssignment: 'ReviewAssignment',
  Team: 'Team',
  TeamMember: 'TeamMember',
  TeamAction: 'TeamAction',
  Notification: 'Notification',
  WebhookConfig: 'WebhookConfig',
  ScheduledScanConfig: 'ScheduledScanConfig',
  ScheduledScanRun: 'ScheduledScanRun',
  GitHubComment: 'GitHubComment',
  GitHubStatusCheck: 'GitHubStatusCheck',
  BranchProtectionRecommendation: 'BranchProtectionRecommendation',
  Diagram: 'Diagram',
  ReviewRule: 'ReviewRule',
  SystemSettings: 'SystemSettings',
  SupportMessage: 'SupportMessage',
  AuditLog: 'AuditLog',
  SsoProvider: 'SsoProvider',
  CustomRole: 'CustomRole',
  UserCustomRole: 'UserCustomRole',
  Discount: 'Discount',
  UserPriceOverride: 'UserPriceOverride',
  PartnerDomain: 'PartnerDomain',
  PricingPlan: 'PricingPlan',
  Capability: 'Capability',
  PlanCapability: 'PlanCapability',
  PricingSettings: 'PricingSettings',
  Invoice: 'Invoice',
  PaymentEvent: 'PaymentEvent',
  WebhookDedup: 'WebhookDedup',
  UserDiscount: 'UserDiscount',
  BillingInfo: 'BillingInfo',
  PaymentMethod: 'PaymentMethod',
  LegalPage: 'LegalPage',
  ContactMessage: 'ContactMessage',
  EmailTemplate: 'EmailTemplate'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
